[voyager]
network = "mainnet"
license = "BUSL-1.1"
lock-file = true
verbose = true
watch = true

[[contracts]]
class-hash = "0x0079c62b9e8e26527d1cfd9721e4bbe82a181212d8c4ce0bd9ef36214fe53653"
contract-name = "abbot"

[[contracts]]
class-hash = "0x052a9ba5a266efdf81e72d57927d45d32b2cd4ed9e01743a7d58bc1ce406cb3f"
contract-name = "absorber"

[[contracts]]
class-hash = "0x06ef29626195cfbb2522b695f27c9f7f3a0c71b1f3895cdac9ff72a356bb1760"
contract-name = "caretaker"

[[contracts]]
class-hash = "0x00757b0a734118b77ca0ef8298c904dc4d6dd1112a74b89f762e64578c5dd61e"
contract-name = "controller"

[[contracts]]
class-hash = "0x07ad19eba012a12147cd91b475c22d75c47b6f59eb09ed18c27bb967477073ce"
contract-name = "equalizer"

[[contracts]]
class-hash = "0x06087367be9b1f5e65df2bfb5b7a00010c4b0e85fc1da998b510dfda61420b31"
contract-name = "flash_mint"

[[contracts]]
class-hash = "0x00af217ac88042025de06ba64d713509e287c4bab56234826083432e2ec58a52"
contract-name = "gate"

[[contracts]]
class-hash = "0x020edc26d65626a79f17d96e07d638b790c57435f9ffe0b1c446cc617a1b2d82"
contract-name = "purger"

[[contracts]]
class-hash = "0x0242c26b828af0e6dbef60b84e300a257c81c990c52cf0486a39c061e701e23a"
contract-name = "sentinel"

[[contracts]]
class-hash = "0x037ee302be6f4e4f166c90662fa346241667da86d6690d7704d96b790eb796cf"
contract-name = "shrine"

